name: build image, attach SBOMs, sign and push

on:
  workflow_call:


jobs:
  attach-sboms-and-sign-image:
    permissions:
      id-token: write
      contents: write # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Download node SBOM
        uses: actions/download-artifact@v4
        with:
          name: node-sbom.json
      - name: Download container SBOM
        uses: actions/download-artifact@v4
        with:
          name: container-sbom.json
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        id: build
        with:
          push: true
          tags: smikesword/tindahan-wise-api:v1.0.0
      - name: Install cosign
        uses: sigstore/cosign-installer@v4.0.0
      - name: attest/attach node sbom to image
        run: |
          cosign attest \
          --predicate node-sbom.json \
          --type cyclonedx \
          smikesword/tindahan-wise-api@${{ steps.build.outputs.digest }}
      - name: attest/attach container sbom to image
        run: |
          cosign attest \
          --predicate container-sbom.json \
          --type cyclonedx \
          smikesword/tindahan-wise-api@${{ steps.build.outputs.digest }}
      - name: Sign the image
        run: |
          cosign sign smikesword/tindahan-wise-api@${{ steps.build.outputs.digest }}
